### ISSUE TITLE
requirements.txt with directory

### ISSUE THREAD

**Issue by kenmlee** [docker-library/django#9]
Hi.
I'm using requirements.txt with requirements directory structure. But your Dockerfile COPY command only copied requirements.txt file without requirements directory.

The content of my requirements.txt file is:
-------------------------------------------------------------------------------------
-r requirements/dev.txt
-------------------------------------------------------------------------------------
and the structure of my requirements directory is:
-------------------------------------------------------------------------------------
--requirements
          |- common.txt
          |- dev.txt
          |- prod.txt
          |- test.txt
-------------------------------------------------------------------------------------

You know, pip can support those structure. I hope your image:onbuild also can support it.

Thanks!

**Comment by tianon** [comment]
There's not an easy way for us to implement this kind of complex support using `ONBUILD` alone, which is why the updated descriptions explain that the `:onbuild` variants are specifically to help jump-start the majority of projects, but as your project requirements grow you'll likely want to switch off them to something more explicit.  See https://github.com/docker-library/ruby/issues/22 for a similar issue discussing Ruby's `Gemfile` support for loading additional files in this same way.

**Comment by yosifkit** [comment]
Duplicate: https://github.com/docker-library/django/issues/7
